version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: monday
      time: '02:00'
      timezone: Asia/Shanghai
    open-pull-requests-limit: 10
    labels:
      - deps
      - security
    ignore:
      - dependency-name: node
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
      day: monday
      time: '02:30'
      timezone: Asia/Shanghai
    labels:
      - deps
      - github-actions
